name: mendeleydesktop
version: 1.19.8
summary: Mendeley reference manager.
description: |
  Mendeley brings your research to life, so you can make an impact on tomorrow.
base: core20
grade: stable
confinement: strict

architectures:
  - build-on: amd64

parts:
  mendeleydesktop:
    plugin: dump
    source: https://desktop-download.mendeley.com/download/linux/mendeleydesktop-1.19.8-linux-x86_64.tar.bz2
#    source-type: bzr
#    source: https://desktop-download.mendeley.com/download/apt/pool/main/m/mendeleydesktop/mendeleydesktop_1.19.8-stable_amd64.deb
#    source-type: deb
#    stage-packages:

apps:
  mendeleydesktop:
    command: bin/mendeleydesktop
    plugs:
    - home

