name: ansible
version: "2.13"
summary: Red Hat Ansible Automation Platform
description: |
  Red Hat® Ansible® Automation Platform is a foundation for building and operating automation across an organization. The platform includes all the tools needed to implement enterprise-wide automation
base: core20
grade: stable
confinement: strict

architectures:
  - build-on: amd64

parts:
  # https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#running-the-devel-branch-from-a-clone
  ansible:
    source: https://github.com/ansible/ansible.git
    source-type: git
    source-branch: "stable-${SNAPCRAFT_PROJECT_VERSION}"
    plugin: python
    requirements:
      - requirements.txt
#    stage-packages:
#      - python3-argcomplete
# With nil plugin
#    plugin: nil
#    override-build: |
#      cd ansible
#      source ./hacking/env-setup
#      # If you want to suppress spurious warnings/errors, use:
#      # source ./hacking/env-setup -q
#      # If you do not have pip installed in your version of Python, install it:
#      curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
#      python get-pip.py --user
#      # Ansible also uses the following Python modules that need to be installed
#      python -m pip install --user -r ./requirements.txt
#    build-packages:
#      - python3
#    stage-packages:
#      - python3
#      - python3-argcomplete
# With ppa repository:
# https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#installing-ansible-on-debian

# Needed aliases:
# sudo snap alias ansible.config ansible-config
# sudo snap alias ansible.config ansible-config
# sudo snap alias ansible.connection ansible-connection
# sudo snap alias ansible.console ansible-console
# sudo snap alias ansible.galaxy ansible-galaxy
# sudo snap alias ansible.inventory ansible-inventory
# sudo snap alias ansible.playbook ansible-playbook
# sudo snap alias ansible.pull ansible-pull
# sudo snap alias ansible.test ansible-test
# sudo snap alias ansible.vault ansible-vault
apps:
  ansible:
    command: bin/ansible
    plugs:
    - home
  config:
    command: bin/ansible-config
    plugs:
    - home
  connection:
    command: bin/ansible-connection
    plugs:
    - home
  console:
    command: bin/ansible-console
    plugs:
    - home
  galaxy:
    command: bin/ansible-galaxy
    plugs:
    - home
  inventory:
    command: bin/ansible-inventory
    plugs:
    - home
  playbook:
    command: bin/ansible-playbook
    plugs:
    - home
  pull:
    command: bin/ansible-pull
    plugs:
    - home
  test:
    command: bin/ansible-test
    plugs:
    - home
  vault:
    command: bin/ansible-vault
    plugs:
    - home
