name: gpgme
version: 1.17.1
summary: Red Hat Ansible Automation Platform
description: |
  GnuPG Made Easy (GPGME) is a library designed to make access to GnuPG easier for applications. It provides a High-Level Crypto API for encryption, decryption, signing, signature verification and key management. Currently it uses GnuPG as its backend but the API isn't restricted to this engine; in fact we have already developed a backend for CMS (S/MIME).

  Because the direct use of GnuPG from an application can be a complicated programming task, it is suggested that all software should try to use GPGME instead. This way bug fixes or improvements can be done at a central place and every application benefits from this.

  Especially authors of MUAs should consider to use GPGME.
base: core20
grade: stable
confinement: strict

architectures:
  - build-on: amd64

parts:
  gpgme:
    source: https://dev.gnupg.org/source/gpgme.git
    source-type: git
    source-tag: "gpgme-${SNAPCRAFT_PROJECT_VERSION}"
    plugin: make

apps:
  ansible:
    command: usr/local/bin/gpgme
    plugs:
    - home
